services:
  db:
    container_name: pkrbt-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pkrbt
      POSTGRES_PASSWORD: pkrbt
      POSTGRES_USER: pkrbt
    volumes:
      - ./vars/postgres:/var/lib/postgresql/data:rw
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=pkrbt"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  redis:
    container_name: pkrbt-redis
    image: redis:7-alpine
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    container_name: pkrbt-api
    image: directus/directus:11.2.1
    ports:
      - 8055:8055
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./vars/directus/database:/directus/database
      - ./vars/directus/uploads:/directus/uploads
      - ./vars/directus/extensions:/directus/extensions
    env_file: .env
