packages:
  - apps/**
  - packages/**

catalog:
  '@types/bun': ^1.3.8
  '@types/node': 25.2.1
  '@vitest/coverage-istanbul': 4.0.18
  '@vitest/ui': ^4.0.18
  tsdown: ^0.20.1
  typescript: ^5.9.3
  vitest: ^4.0.18
  vitest-mock-extended: ^3.1.0

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 43200
