name: Collect Changes
description: Collect changes from commit

outputs:
  web:
    description: Website code changed
    value: ${{ steps.filter.outputs.web }}
  pwa:
    description: PWA code changed
    value: ${{ steps.filter.outputs.pwa }}
  node_test:
    description: Require node tests
    value: ${{ steps.filter.outputs.node_test }}
  environment:
    description: Environment
    value: ${{ steps.vars.outputs.environment }}

runs:
  using: composite
  steps:
    - name: Collect changed files
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          pwa:
            - "apps/pwa/**"
          web:
            - "apps/web/**"
          node_test:
            - ".github/workflows/node-test.yml"
            - ".github/actions/setup-node/**"
            - "apps/web/**"
            - "apps/pwa/**"
