name: CD

on:
  push:
    branches:
      - next
      - main

# These are recommended by the semantic-release docs: https://github.com/semantic-release/npm#npm-provenance
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  packages: write
  deployments: write
  statuses: write

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  build:
    name: Build
    uses: paroki/pkrbt/.github/workflows/build.yml@next
    secrets: inherit
    with:
      environment: development

  deploy:
    name: Deploy
    needs: ["build"]
    uses: paroki/pkrbt/.github/workflows/deploy.yml@next
    secrets: inherit
    with:
      environment: development
