name: CD

on:
  push:
    branches:
      - next

# These are recommended by the semantic-release docs: https://github.com/semantic-release/npm#npm-provenance
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  packages: write
  deployments: write
  statuses: write

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  changes:
    name: Collect Changes
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.vars.outputs.web }}
      pwa: ${{ steps.vars.outputs.pwa }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect changes
        uses: ./.github/actions/collect-changes
        id: vars

  #build:
  #  name: Build
  #  needs: ["changes"]
  #  uses: paroki/pkrbt/.github/workflows/build.yml@next
  #  secrets: inherit
  #  with:
  #    environment: development
  #    cms: ${{ needs.changes.outputs.build_cms }}

  deploy:
    name: Deploy
    needs: ["changes"]
    uses: paroki/pkrbt/.github/workflows/deploy.yml@next
    secrets: inherit
    with:
      environment: development
      web: ${{ needs.changes.outputs.web }}
      pwa: "true"
