name: CI

on:
  push:
    branches:
      - next
      - main
  pull_request:
    branches:
      - next
      - main
  workflow_dispatch: ~
  schedule:
    - cron: 0 2 * * 0

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: Collect Changes
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.vars.outputs.api }}
      cms: ${{ steps.vars.outputs.cms }}
      web: ${{ steps.vars.outputs.web }}
      pwa: ${{ steps.vars.outputs.pwa }}
      node_test: ${{ steps.vars.outputs.node_test }}
      build_cms: ${{ steps.vars.outputs.build_cms }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect changes
        uses: ./.github/actions/collect-changes
        id: vars

  node-test:
    name: NodeJS
    needs: ["changes"]
    uses: paroki/pkrbt/.github/workflows/node-test.yml@next
    secrets: inherit
    with:
      node_test: ${{ needs.changes.outputs.node_test }}

  e2e:
    name: E2E
    needs: ["changes"]
    uses: paroki/pkrbt/.github/workflows/e2e.yml@next
    secrets: inherit
    with:
      node_test: ${{ needs.changes.outputs.node_test }}
      web: ${{ needs.changes.outputs.web }}
