name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Production release
        default: "development"
      ref_name:
        type: string
        description: Version to deploy
        default: ${{ github.ref_name }}
      web:
        type: string
        description: Build Website
        default: "false"

permissions:
  contents: read
  deployments: write
  statuses: write
  pull-requests: write

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
  TURBO_REMOTE_ONLY: true
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  web:
    name: Website
    runs-on: ubuntu-latest
    if: inputs.web == 'true'
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_ID }}
    environment: ${{ inputs.environment }}
    steps:
      - name: setup vars
        id: vars
        shell: bash
        run: |
          vercel_deploy="vercel deploy --prebuilt"
          vercel_build="vercel build"
          vercel_env="development"
          env="${{ inputs.environment }}"
          version="${{ inputs.ref_name }}@${{ github.sha }}"
          if [[ $env == "production" ]]; then
            vercel_deploy="vercel deploy --prod --prebuilt"
            vercel_build="vercel build --prod"
            vercel_env="production"
            version="${{ inputs.ref_name }}"
          fi

          echo "vercel_deploy=${vercel_deploy}" >> $GITHUB_OUTPUT
          echo "vercel_build=${vercel_build}" >> $GITHUB_OUTPUT
          echo "vercel_env=${vercel_env}" >> $GITHUB_OUTPUT
          echo "NEXT_PUBLIC_VERSION=${version}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest
          npm install -g turbo

      - name: Pull Vercel Environment Information
        run: |
          vercel pull \
            --yes \
            --environment=${{ steps.vars.outputs.vercel_env }} \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          pnpm build --filter=@pkrbt/web
          ${{ steps.vars.outputs.vercel_build }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          ${{ steps.vars.outputs.vercel_deploy }} --token=${{ secrets.VERCEL_TOKEN }}
