name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to (e.g., 'development', 'production')"
        type: string
        default: "development"

permissions:
  contents: read
  deployments: write
  statuses: write
  pull-requests: write

jobs:
  deploy:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: web
            name: Website
          - path: dashboard
            name: Dashboard

    steps:
      - name: setup vars
        id: vars
        shell: bash
        run: |
          vercel_deploy="vercel deploy --prebuilt"
          vercel_build="vercel build"
          vercel_env="${{ inputs.environment }}"
          version="${{ github.ref_name }}@${{ github.sha }}"
          project_id="${{ secrets.VERCEL_WEB_PROJECT_ID }}"

          if [[ $vercel_env == "production" ]]; then
            vercel_deploy="vercel deploy --prod --prebuilt"
            vercel_build="vercel build --prod"
            version="${{ github.ref_name }}"
          fi

          if [[ ${{ matrix.path }} == "dashboard" ]]; then
            project_id="${{ secrets.VERCEL_DASHBOARD_PROJECT_ID }}"
          fi

          echo "vercel_deploy=${vercel_deploy}" >> $GITHUB_OUTPUT
          echo "vercel_build=${vercel_build}" >> $GITHUB_OUTPUT
          echo "vercel_env=${vercel_env}" >> $GITHUB_OUTPUT
          echo "project_id=${project_id}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install Vercel CLI
        run: |
          pnpm add -g vercel@latest
          pnpm add -g turbo

      - name: Pull Vercel Environment Information
        run: |
          vercel pull \
            --yes \
            --environment=${{ steps.vars.outputs.vercel_env }} \
            --token=${{ secrets.VERCEL_TOKEN }}
          pnpm build --filter=@pkrbt/${{ matrix.path }}
          ${{ steps.vars.outputs.vercel_build }} --token=${{ secrets.VERCEL_TOKEN }}
          ${{ steps.vars.outputs.vercel_deploy }} --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ steps.vars.outputs.project_id }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
