name: E2E Testing

on:
  workflow_call:
    inputs:
      node_test:
        type: string
        description: Runs node test
        default: "false"
      web:
        type: string
        description: Runs web test
        default: "false"

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
  TURBO_REMOTE_ONLY: true
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  web:
    name: Website
    if: inputs.web == 'true' && inputs.node_test == 'true'
    runs-on: ubuntu-latest
    env:
      DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
      NEXT_PUBLIC_DIRECTUS_URL: ${{ secrets.NEXT_PUBLIC_DIRECTUS_URL }}
      NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Build
        shell: bash
        run: |
          pnpm build --filter=@pkrbt/web

      #- name: Check HTTP reachability
      #  shell: bash
      #  run: |
      #    until curl --output /dev/null --silent --head --fail http://localhost:8055/server/ping; do printf '.'; sleep 5; done

      - name: Start dev server
        run: pnpm start &

      - name: Install Playwright Browsers
        working-directory: ./apps/web
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm e2e --filter=@pkrbt/web

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: web-playwright-report
          path: ./apps/web/playwright-report/
          retention-days: 30
