name: Test

on:
  workflow_call:
    inputs:
      node_test:
        type: string
        description: Runs node test
        default: "false"

env:
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
  TURBO_REMOTE_ONLY: true
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  vitest:
    name: Vitest
    if: inputs.node_test == 'true'
    runs-on: ubuntu-latest
    environment: "development"
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
      TURBO_REMOTE_ONLY: true
      DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
      NEXT_PUBLIC_DIRECTUS_URL: ${{ secrets.NEXT_PUBLIC_DIRECTUS_URL }}
      NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: copy env vars
        shell: bash
        run: |
          cp apps/web/.env.default apps/web/.env.test

      - name: test with coverage
        shell: bash
        run: |
          pnpm coverage

      - name: upload directus coverage
        uses: codecov/codecov-action@v4
        with:
          flags: directus # optional
          name: directus # optional
          files: ./clover.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true
          directory: ./packages/directus/coverage

      - name: upload directus-core coverage
        uses: codecov/codecov-action@v4
        with:
          flags: directus-core # optional
          name: directus-core # optional
          files: ./clover.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true
          directory: ./packages/directus-core/coverage

      - name: upload web coverage
        uses: codecov/codecov-action@v4
        with:
          flags: web # optional
          name: web # optional
          files: ./clover.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true
          directory: ./apps/web/coverage
