name: Release

on:
  workflow_call:

# These are recommended by the semantic-release docs: https://github.com/semantic-release/npm#npm-provenance
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  packages: write
  deployments: write
  statuses: write

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      ref_name: ${{ steps.vars.outputs.ref_name }}
      environment: ${{ steps.vars.outputs.environment }}
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
      TURBO_CACHE: remote:rw
    steps:
      - shell: bash
        run: |
          echo "Ref name is: ${{ github.ref_name }}"

      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - id: release
        if: github.ref_name == 'main'
        run: |
          pnpm add -g semantic-release
          pnpm add -D @semantic-release/changelog @semantic-release/git @semantic-release/exec --workspace-root
          pnpx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - id: vars
        shell: bash
        run: |
          ref_name="next"
          environment="development"

          if [[ ${{ github.ref_name }} == 'main' ]]; then
            ref_name="${{ steps.release.outputs.version }}"
            environment="production"
          fi
          echo "ref_name=${ref_name}" >> $GITHUB_OUTPUT
          echo "environment=${environment}" >> $GITHUB_OUTPUT

  deploy:
    name: ${{ matrix.name }}
    needs: [release]
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
      TURBO_CACHE: remote:rw
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: web
            name: Website
          - path: dashboard
            name: Dashboard

    steps:
      - name: setup vars
        id: vars
        shell: bash
        run: |
          vercel_deploy="vercel deploy --prebuilt"
          vercel_build="vercel build"
          vercel_env="${{ needs.release.outputs.environment }}"
          version="${{ github.ref_name }}@${{ github.sha }}"
          project_id="${{ secrets.VERCEL_WEB_PROJECT_ID }}"

          if [[ $vercel_env == "production" ]]; then
            vercel_deploy="vercel deploy --prod --prebuilt"
            vercel_build="vercel build --prod"
            version="${{ needs.release.outputs.ref_name }}"
          fi

          if [[ ${{ matrix.path }} == "dashboard" ]]; then
            project_id="${{ secrets.VERCEL_DASHBOARD_PROJECT_ID }}"
          fi

          echo "vercel_deploy=${vercel_deploy}" >> $GITHUB_OUTPUT
          echo "vercel_build=${vercel_build}" >> $GITHUB_OUTPUT
          echo "vercel_env=${vercel_env}" >> $GITHUB_OUTPUT
          echo "project_id=${project_id}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install Vercel CLI
        run: |
          pnpm add -g vercel@latest
          pnpm add -g turbo

      - name: Pull Vercel Environment Information
        run: |
          vercel pull \
            --yes \
            --environment=${{ steps.vars.outputs.vercel_env }} \
            --token=${{ secrets.VERCEL_TOKEN }}
          pnpm build --filter=@pkrbt/${{ matrix.path }}
          ${{ steps.vars.outputs.vercel_build }} --token=${{ secrets.VERCEL_TOKEN }}
          ${{ steps.vars.outputs.vercel_deploy }} --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ steps.vars.outputs.project_id }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
