name: Release

on:
  workflow_call:

# These are recommended by the semantic-release docs: https://github.com/semantic-release/npm#npm-provenance
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  packages: write
  deployments: write
  statuses: write

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      ref_name: ${{ steps.vars.outputs.ref_name }}
      environment: ${{ steps.vars.outputs.environment }}
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
      TURBO_CACHE: remote:rw
    steps:
      - shell: bash
        run: |
          echo "Ref name is: ${{ github.ref_name }}"

      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - id: release
        if: github.ref_name == 'main'
        run: |
          pnpm add -g semantic-release
          pnpm add -D @semantic-release/changelog @semantic-release/git @semantic-release/exec --workspace-root
          pnpx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - id: vars
        shell: bash
        run: |
          ref_name="next"
          environment="development"

          if [[ ${{ github.ref_name }} == 'main' ]]; then
            ref_name="${{ steps.release.outputs.version }}"
            environment="production"
          fi
          echo "ref_name=${ref_name}" >> $GITHUB_OUTPUT
          echo "environment=${environment}" >> $GITHUB_OUTPUT
