name: Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
      TURBO_CACHE: remote:rw
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install eslint
        shell: bash
        run: |
          pnpm add --global eslint

      - name: test with coverage
        shell: bash
        run: |
          pnpm lint

  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
      TURBO_CACHE: remote:rw
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: test with coverage
        shell: bash
        run: |
          pnpm coverage

      - name: upload dashboard coverage
        uses: codecov/codecov-action@v5
        with:
          flags: dashboard # optional
          name: dashboard # optional
          files: clover.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true
          directory: ./apps/dashboard/coverage

      - name: upload web coverage
        uses: codecov/codecov-action@v5
        with:
          flags: web # optional
          name: web # optional
          files: clover.xml
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true
          directory: ./apps/web/coverage

  e2e:
    name: E2E Tests
    needs: ["lint", "vitest"]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
      TURBO_CACHE: remote:rw
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Load Playwright Browsers Cache
        uses: actions/cache@v4
        id: playwright-browsers-cache
        with:
          path: ~/.cache/ms-playwright # Adjust path based on OS if needed
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/pnpm-lock.yaml') }} }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      - name: Install Playwright Browsers
        if: steps.playwright-browsers-cache.outputs.cache-hit != 'true'
        run: pnpx playwright install --with-deps
        working-directory: apps/web

      - name: Run Playwright tests
        run: pnpm e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: e2e
          path: playwright-report/
          retention-days: 30
